"""Report generation: structured JSON and a self-contained HTML dashboard.

Both are produced from the same ScanResult object so they always agree.
The HTML report is a single file with inline CSS (no external assets), which
makes it easy to share, archive, or attach to a ticket.
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from typing import Optional
import os

# Optional JSON Schema validation (requires `jsonschema` package)
_SCHEMA_PATH = os.path.join(os.path.dirname(__file__), "report_schema.json")
try:
    import jsonschema  # type: ignore

    _HAS_JSONSCHEMA = True
except Exception:
    _HAS_JSONSCHEMA = False

from .models import Level, ScanResult

LEVEL_BADGE = {
    Level.PASS: "#15803d",
    Level.WARN: "#b45309",
    Level.FAIL: "#b91c1c",
    Level.INFO: "#1d4ed8",
    Level.SKIP: "#6b7280",
}

LEVEL_LABEL = {
    Level.PASS: "Pass",
    Level.WARN: "Warning",
    Level.FAIL: "Fail",
    Level.INFO: "Info",
    Level.SKIP: "Skipped",
}


def to_json(result: ScanResult, pretty: bool = True) -> str:
    return json.dumps(result.to_dict(), indent=2 if pretty else None)


def to_html(result: ScanResult) -> str:
    rows = []
    for c in result.checks:
        color = LEVEL_BADGE.get(c.level, "#374151")
        label = LEVEL_LABEL.get(c.level, c.level.value)
        rows.append(
            f"<tr><td class='mono'>{html.escape(c.id)}</td>"
            f"<td>{html.escape(c.title)}</td>"
            f"<td>{html.escape(c.category)}</td>"
            f"<td class='mono'>{html.escape(c.cis_ref)}</td>"
            f"<td><span class='badge' style='background:{color}'>{label}</span></td>"
            f"<td>{html.escape(c.detail)}</td></tr>"
        )
    open_ports_rows = "".join(
        f"<tr><td class='mono'>{p['port']}</td><td>{html.escape(p['service'])}</td></tr>"
        for p in result.open_ports
    )
    if not result.open_ports:
        open_ports_rows = "<tr><td colspan='2' class='muted'>No open ports found in the scanned range.</td></tr>"

    summary = ", ".join(
        f"{LEVEL_LABEL[lvl]}: {sum(1 for c in result.checks if c.level == lvl)}"
        for lvl in (Level.PASS, Level.WARN, Level.FAIL, Level.INFO, Level.SKIP)
    )

    html_doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Security Audit Report — {html.escape(result.host)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         margin: 32px; color: #111827; background: #f9fafb; }}
  h1 {{ margin-bottom: 4px; }} .muted {{ color: #6b7280; }}
  .mono {{ font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.85em; }}
  .badge {{ color:#fff; padding:2px 8px; border-radius:999px; font-size:0.78em; font-weight:600; }}
  table {{ border-collapse: collapse; width: 100%; background:#fff; margin-top:16px; }}
  th, td {{ border-bottom: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; vertical-align: top; }}
  th {{ background:#f3f4f6; font-size:0.82em; text-transform:uppercase; letter-spacing:0.03em; }}
  .meta {{ font-size:0.9em; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:12px; margin-top:12px; }}
  .card {{ background:#fff; border:1px solid #e5e7eb; border-radius:8px; padding:14px; }}
  .big {{ font-size:1.6em; font-weight:700; }}
</style></head><body>
  <h1>Security Audit Report</h1>
  <div class="muted">Host: <span class="mono">{html.escape(result.host)}</span></div>
  <div class="meta">
    Started: {html.escape(result.started_at)} &nbsp;•&nbsp;
    Finished: {html.escape(result.finished_at)} &nbsp;•&nbsp;
    Duration: {result.duration_ms} ms &nbsp;•&nbsp; Checks: {len(result.checks)}
  </div>
  <div class="grid">
    <div class="card"><div class="big">{result.score}</div><div class="muted">Hardening Score (0-100)</div></div>
    <div class="card"><div class="big">{len(result.checks)}</div><div class="muted">Checks Run</div></div>
    <div class="card"><div class="big">{len(result.open_ports)}</div><div class="muted">Open Ports Found</div></div>
    <div class="card"><div class="big">{result.duration_ms} ms</div><div class="muted">Scan Duration</div></div>
  </div>
  <h2>Configuration Checks</h2>
  <p class="muted">{summary}</p>
  <table>
    <thead><tr><th>ID</th><th>Check</th><th>Category</th><th>CIS Ref</th><th>Result</th><th>Detail</th></tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table>
  <h2>Open Ports ({len(result.open_ports)})</h2>
  <table><thead><tr><th>Port</th><th>Service</th></tr></thead><tbody>{open_ports_rows}</tbody></table>
  <p class="muted" style="margin-top:24px">Generated by security-audit-tool on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.</p>
</body></html>"""
    return html_doc


def write_reports(result: ScanResult, out_dir: str) -> dict:
    """Write JSON + HTML report files and return the created paths."""
    import os

    os.makedirs(out_dir, exist_ok=True)
    # Validate report against schema when available
    if _HAS_JSONSCHEMA:
        try:
            with open(_SCHEMA_PATH, "r", encoding="utf-8") as fh:
                schema = json.load(fh)
            jsonschema.validate(instance=result.to_dict(), schema=schema)
        except Exception as exc:
            raise RuntimeError(f"report validation failed: {exc}")
    base = f"audit_{result.host}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    json_path = os.path.join(out_dir, base + ".json")
    html_path = os.path.join(out_dir, base + ".html")
    with open(json_path, "w", encoding="utf-8") as fh:
        fh.write(to_json(result))
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(to_html(result))
    return {"json": json_path, "html": html_path}
